### ISSUE TITLE
Use the steam:\\ Protocol in order to add friends from the web ( add friend buttons)

### ISSUE THREAD

**Issue by doodla** [waylaidwanderer/Mist#16]

**Comment by waylaidwanderer** [comment]
This requires Steam to be open. What's the benefit of this over the current implementation?

**Comment by waylaidwanderer** [comment]
Quoting from your Reddit post:

> Would it be possible to associate steam:\ protocol with the app? So we can add friends directly from outpost and other sites?

No. This requires writing to the registry, which would also take over Steam's handling of steam:\ permanently. This defeats the purpose of Mist as it's meant to be a portable application.
