### ISSUE TITLE
"Submit Chat Log" button or context menu

### ISSUE THREAD

**Issue by Jamyn** [waylaidwanderer/Mist#21]
It'd be useful if we could provide a one-click "Submit chat log to SteamRep" option.  Even if the logs don't go directly to SteamRep, the ability to collect and archive logs from questionable transactions would be useful.

We could potentially include data like:
1. Trade time(s)
2. Trade items (with Item IDs?)
3. IP of remote user (not sure if this is exposed in SteamBot)
4. our id64; the id64 of the other participant
5. Current date/time in GMT

... not sure what other information would be useful. But essentially, simplifying log collection and submission would probably be a nice (long-term) feature.

**Comment by waylaidwanderer** [comment]
I was thinking of adding all that stuff to the chat log, actually. Basically whenever you start a trade with someone it will append
`==========TRADE STARTED [maybe with date-time?]==========`
and then we can add the info you suggested, and when the trade is ended append
`==========TRADE ENDED [maybe with date-time?]==========`
so we don't need separate logs for chatting and trading
