### ISSUE TITLE
Native Trading with Mist

### ISSUE THREAD

**Issue by waylaidwanderer** [waylaidwanderer/Mist#22]
This has been frustrating me to no end so I'm just going to leave it here as an issue for now.

I'm trying to get native trading to work, i.e. when in trade, open the Steam trade page (http://steamcommunity.com/trade/STEAMID) in a webbrowser control (**with the correct cookies**) so that we can bypass using Mist's trading GUI. This of course will make trading 100% secure in that there is no chance of Mist messing up and not logging a trade event since everything will be handled via Steam directly.

Anyway, it's not working, and I have no good way to get it to work.

**Comment by nosoop** [comment]
Hello there!

Might be a silly comment to bring this up a year late, but if I'm looking correctly (which I sure as hell might not be; I'm not C# proficient at all), under ShowTrade_Web.cs, you're adding the steamMachineAuth cookie for profile 76561198065838051, which may or may not be the account you're using with Mist.

Other than that, the only two cookies that I _think_ you actually really need are "sessionid" and "steamLogin"; can't tell if those are passed over, but the string values to grab off of SteamBot.Bot are "sessionid" and "token", respectively.

Anything showing up in the browser control, if getting there at all, or is it some other issue that actually doesn't relate to the cookies?

**Comment by waylaidwanderer** [comment]
You're right, but I was just using that for testing and playing around with.

However, I decided to be more serious about it and actually try to get it working, and amazingly I _just_ managed to get it to work properly, so I'm excited to say that native web trading will be coming soon to Mist! This will solve many issues with trading (more secure and reliable) at the cost of losing features such as being able to get the value of both user's offered items, but I'm sure nobody will mind.

**Comment by waylaidwanderer** [comment]
Added in commit 939c558fbcbcfc248fccd7d41cdc5d7e890a8ac2.
