### ISSUE TITLE
Mist crashing in 3.1.0

### ISSUE THREAD

**Issue by SSlotts** [waylaidwanderer/Mist#25]
If you change the setting to when you click the 'x' it closes it in this version after closing it and trying to reopen and login it will crash every time rendering it unusable. It does not do this in 3.0.0.

**Comment by waylaidwanderer** [comment]
Can you upload the contents of Mist.log?

SSlotts notifications@github.com wrote:

If you change the setting to when you click the 'x' it closes it in this version after closing it and trying to reopen and login it will crash every time rendering it unusable. It does not do this in 3.0.0.

---

Reply to this email directly or view it on GitHub:
https://github.com/waylaidwanderer/Mist/issues/25

**Comment by SSlotts** [comment]
Hmm actually may not be caused by this. I just tested it again and it seems to crash for me after I update.

Here is the log:

[Mist 2013-03-28 14:34:27] INFO: Launching Mist...
[Mist 2013-03-28 14:34:47] DEBUG: Initializing Steam account...
[Mist 2013-03-28 14:34:47] INFO: Connecting...
[Mist 2013-03-28 14:34:47] DEBUG: SteamKit2.SteamClient+ConnectedCallback
[Mist 2013-03-28 14:34:47] DEBUG: Connection Callback: OK
[Mist 2013-03-28 14:34:48] DEBUG: SteamKit2.SteamUser+LoggedOnCallback
[Mist 2013-03-28 14:34:48] DEBUG: Logged On Callback: AccountLogonDenied
[Mist 2013-03-28 14:34:48] ERROR: Login Error: AccountLogonDenied
[Mist 2013-03-28 14:34:48] INTERFACE: This account is protected by Steam Guard.  Enter the authentication code sent to the proper email: 
[Mist 2013-03-28 14:34:52] INFO: [UPDATER] Beginning the update process...
[Mist 2013-03-28 14:34:53] INFO: [UPDATER] Extracting zip file...
[Mist 2013-03-28 14:34:53] INFO: [UPDATER] Renamed Mist.exe to prepare for deletion.
[Mist 2013-03-28 14:34:53] INFO: [UPDATER] Extracting Mist.exe...
[Mist 2013-03-28 14:34:54] SUCCESS: [UPDATER] Mist has been successfully updated!
[Mist 2013-03-28 14:34:57] INFO: Launching Mist...
[Mist 2013-03-28 14:35:07] DEBUG: Initializing Steam account...
[Mist 2013-03-28 14:35:07] INFO: Connecting...
[Mist 2013-03-28 14:35:07] DEBUG: SteamKit2.SteamClient+ConnectedCallback
[Mist 2013-03-28 14:35:07] DEBUG: Connection Callback: OK
[Mist 2013-03-28 14:35:08] DEBUG: SteamKit2.SteamUser+LoggedOnCallback
[Mist 2013-03-28 14:35:08] DEBUG: Logged On Callback: AccountLogonDenied
[Mist 2013-03-28 14:35:08] ERROR: Login Error: AccountLogonDenied
[Mist 2013-03-28 14:35:08] INTERFACE: This account is protected by Steam Guard.  Enter the authentication code sent to the proper email: 
[Mist 2013-03-28 14:35:16] DEBUG: SteamKit2.SteamClient+DisconnectedCallback
[Mist 2013-03-28 14:35:16] WARN: Disconnected from Steam Network!
[Mist 2013-03-28 14:35:16] DEBUG: SteamKit2.SteamClient+ConnectedCallback
[Mist 2013-03-28 14:35:16] DEBUG: Connection Callback: OK
[Mist 2013-03-28 14:35:17] DEBUG: SteamKit2.SteamUser+LoggedOnCallback
[Mist 2013-03-28 14:35:17] DEBUG: Logged On Callback: OK
[Mist 2013-03-28 14:35:17] DEBUG: SteamKit2.SteamUser+AccountInfoCallback
[Mist 2013-03-28 14:35:17] DEBUG: SteamKit2.SteamUser+AccountInfoCallback
[Mist 2013-03-28 14:35:17] DEBUG: SteamKit2.SteamApps+VACStatusCallback
[Mist 2013-03-28 14:35:17] DEBUG: SteamKit2.SteamFriends+FriendsListCallback
[Mist 2013-03-28 14:35:17] DEBUG: SteamKit2.SteamApps+LicenseListCallback
[Mist 2013-03-28 14:35:17] DEBUG: SteamKit2.SteamApps+GuestPassListCallback
[Mist 2013-03-28 14:35:17] DEBUG: SteamKit2.SteamUser+WalletInfoCallback
[Mist 2013-03-28 14:35:17] DEBUG: SteamKit2.SteamApps+GameConnectTokensCallback
[Mist 2013-03-28 14:35:17] DEBUG: SteamKit2.SteamUser+SessionTokenCallback
[Mist 2013-03-28 14:35:17] DEBUG: SteamKit2.SteamClient+CMListCallback
[Mist 2013-03-28 14:35:17] DEBUG: SteamKit2.SteamClient+JobCallback`1[SteamKit2.SteamUser+UpdateMachineAuthCallback]
[Mist 2013-03-28 14:35:17] DEBUG: SteamKit2.SteamFriends+PersonaStateCallback
[Mist 2013-03-28 14:35:17] DEBUG: SteamKit2.SteamUser+AccountInfoCallback
[Mist 2013-03-28 14:35:24] DEBUG: SteamKit2.SteamUser+LoginKeyCallback
[Mist 2013-03-28 14:35:24] INFO: About to authenticate...

**Comment by waylaidwanderer** [comment]
Seems like it's crashing when it tries to authenticate. This isn't the first time someone has reported this problem, unfortunately. Can I confirm you have the latest .NET 4.0?

**Comment by SSlotts** [comment]
You stated that .NET 4.0 is required for all versions of MIST and I can run mist version 3.0.0. Also the option to close instead of minimize to tray seems to have to be refreshes as in I have to enable and disable it to close properly in v3.0.0

**Comment by waylaidwanderer** [comment]
If you don't have .NET 4.0 you can run it fine up until a certain point during login. Please see if you can install the latest .NET 4.0 here: http://www.microsoft.com/en-ca/download/details.aspx?id=17851

**Comment by waylaidwanderer** [comment]
Any update on this?

**Comment by SSlotts** [comment]
Well I can run 4 but I did update my .NET so I don't know

**Comment by ghost** [comment]
Waylaid i need to contact you, and this seemed to be the easiest way.. just
HMU on steam

**Comment by waylaidwanderer** [comment]
Good job replying, ash :P Trying to talk to you right now.

@SSlotts I'll mark this as resolved then. If you were able to update to .NET 4.0 then it means you didn't have it installed in the first place.
