### ISSUE TITLE
Count items in trade window

### ISSUE THREAD

**Issue by KrsOne** [waylaidwanderer/Mist#26]
So when you make huge trades (for example selling a S.F. Bat for 34 keys) it gets very hard to read how many keys are put into the window. 

Steam trading also lacks this feature, but at-least it has rows of 4 which helps little.  Mist can act even better then steam when a counter gets added to the trade window.

**Comment by waylaidwanderer** [comment]
Added in commit 939c558fbcbcfc248fccd7d41cdc5d7e890a8ac2.
