### ISSUE TITLE
Ability to Hide Offline Friends

### ISSUE THREAD

**Issue by ghost** [waylaidwanderer/Mist#27]
I know that you can sort by status and do it that way, but then it seperates in-game friends from online friends.  the ability to only show friends who are online/away/busy/in-game/looking to play/trade would be helpful, since it is difficult to discern at a glance.

**Comment by waylaidwanderer** [comment]
I'm working on some other stuff for Mist atm, but I've just implemented this in a patch. Look for it in the updater soon.

**Comment by waylaidwanderer** [comment]
The update is now live.
