### ISSUE TITLE
Not showing strange parts

### ISSUE THREAD

**Issue by KrsOne** [waylaidwanderer/Mist#28]
I trade mainly with strange weapons. I have a huge stock of stranges selling and buying. Sometimes I have stranges that have strange parts. But in the trade window I can't distinguish regular stranges from the ones with strange parts.  

I hope that it will be fixed in the future version

**Comment by waylaidwanderer** [comment]
Fixed with commit 939c558fbcbcfc248fccd7d41cdc5d7e890a8ac2.
