### ISSUE TITLE
Support harvesting from idle alts

### ISSUE THREAD

**Issue by wmassingham** [waylaidwanderer/Mist#30]
I realize this is a big request, but I figure it's something you might like to hack on for a while. :D 

Basically, with the changes to idling, you don't get drops as long as you have items that haven't been placed in the backpack. One solution would be to trade that item out to a main account. So, every so often, run a trade between main and each alt, and move all items (possibly filtered) to the main.

(Actually, I've never used multiple copies of Mist to trade between accounts, only one  Mist and one Steam, so I don't know if Mist actually supports multiple instances.)

**Comment by waylaidwanderer** [comment]
This would really be more of a SteamBot thing and less of a Mist thing. Mist does support multiple instances though.
