### ISSUE TITLE
scam.io is down. Reputation check makes Mist useless atm.

### ISSUE THREAD

**Issue by 6d656368** [waylaidwanderer/Mist#34]
![screen shot 2014-08-20 at 15 31 11](https://cloud.githubusercontent.com/assets/7698234/3980160/68c7e1ea-285e-11e4-8607-d6167b5f7e73.png)
It'll take a while to wait for all those timeouts for every person in friends list.

**Comment by Jamyn** [comment]
I will fix this (scam.io) today. Sorry about that.

**Comment by waylaidwanderer** [comment]
Thanks Jamyn, I appreciate it. Let me know when you've done so and I will close this issue.

**Comment by Jamyn** [comment]
This is fixed. Sorry for the trouble.

**Comment by waylaidwanderer** [comment]
Awesome, thanks a bunch! I should probably make Mist handle timeouts better by working on separate threads for Steamrep checks...
