### ISSUE TITLE
Friends list corruption

### ISSUE THREAD

**Issue by 6d656368** [waylaidwanderer/Mist#35]
Since Mist's friends UI is html based spechial characters in user's names should be escaped.

Here's an example with '> in persona name.
![screen shot 2014-08-20 at 15 45 17](https://cloud.githubusercontent.com/assets/7698234/3980241/92a3fdd6-285f-11e4-9c5a-b7520100e540.png)

**Comment by waylaidwanderer** [comment]
Fixed with commit 6d457c5aeb. Thanks!
