### ISSUE TITLE
Duplicated chat tabs

### ISSUE THREAD

**Issue by 6d656368** [waylaidwanderer/Mist#38]
'Other' persona name change during conversation will cause multiple chat tabs to be created for the same conversation.

```
    foreach (TabPage tab in Friends.chat.ChatTabControl.TabPages)
    {
        if (tab.Text == Bot.SteamFriends.GetFriendPersonaName(OtherSID))
        {
```

Probably should use Tag property to store OtherSID and use it to search for corresponding chat tab.

**Comment by waylaidwanderer** [comment]
Good catch, thanks. There's a lot of old code in Mist that I wrote when I had no idea what I was doing...
